name: push-workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Versions
        run: |
          node -v
          npm -v

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Stash dist
        uses: actions/upload-artifact@master
        with:
          name: dist ${{matrix.node-version}}
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
          registry-url: "https://registry.npmjs.org"

      - name: Unstash dist
        uses: actions/download-artifact@master
        with:
          name: dist 18.x
          path: "dist/"

      - name: Install
        run: npm install

      - name: Publish on NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
